
[font]
size = 14.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "SFMono Nerd Font"
family = "Cousine Nerd Font"
style = "Regular"


[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 14
y = 12

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
#	 "~/.config/alacritty/themes/gruber_darker.toml"
]

[keyboard]
bindings = [
   # Map Super+Number to send custom escape sequence \x1b[N;9~
   # Use \u001b for ESC in TOML strings
   { key = "Key1", mods = "Super", chars = "\u001b[1;9~" },
   { key = "Key2", mods = "Super", chars = "\u001b[2;9~" },
   { key = "Key3", mods = "Super", chars = "\u001b[3;9~" },
   { key = "Key4", mods = "Super", chars = "\u001b[4;9~" },
   { key = "Key5", mods = "Super", chars = "\u001b[5;9~" },
   { key = "Key6", mods = "Super", chars = "\u001b[6;9~" },
   { key = "Key7", mods = "Super", chars = "\u001b[7;9~" },
   { key = "Key8", mods = "Super", chars = "\u001b[8;9~" },
   { key = "Key9", mods = "Super", chars = "\u001b[9;9~" },
   { key = "Key0", mods = "Super", chars = "\u001b[0;9~" },
